"""Initial Migration

Revision ID: 2ac60e7a7ddd
Revises: 
Create Date: 2020-12-08 18:04:42.472515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac60e7a7ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('phonenumber', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'phonenumber')
    # ### end Alembic commands ###
